name: Nodejs deployement to Azure web App. 

on: 
    workflow_dispatch:
    push:
         branches:
            - main

jobs:

    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions@checkout@v3
            - name: setup nodejs environment
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: install dependencies
              run: npm install
            - name: deploy to azure web app
              uses: azure/webapps-deploy@v3
              with:
                app-name: 'nodejs1011'
                publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
                package: .
