name: Deploy NodeJs App To Azure Static App

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source code
              uses: actions/checkout@v4
              with:
                path: .
            - name: build and deploy
              uses: azure/static-web-app-deploy@v1
              with:
                azure_static_web_apps_api_token: ${{secrets.AZURE_STATIC_WEB_APPS_API_TOKEN}}
                app-location: .
                output_location: .
        