name: Deploy NodeJs App To Azure Static App

on:
    workflow_dispatch:
    push:
        branches:
            -master

jobs:
    Source:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source code
              run: actions/checkout@v4
        